name: CI

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo pip3 install -r requirements.txt
    - name: Template out website
      run:  jupyter nbconvert --to notebook --execute "NALZS MAP.ipynb"
    - name: Display html page
      run: ls zoo_map.html