name: CI

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Install requirements
      run: pip3 install -r scripts/requirements.txt --user
    - name: Template out website
      run:  jupyter nbconvert --to notebook --execute "NALZS MAP.ipynb"
    - name: Display html page
      run: ls zoo_map.html